/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.GR3WORK;

import java.io.IOException;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.scene.Parent;



public class App extends Application {

    @Override
    public void start(Stage stage) throws IOException {
        // Load the FXML file
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/LoginScreenUI.fxml"));
        Parent root = loader.load();

        // Set the FXML content in the Scene
        Scene scene = new Scene(root, 800, 600); // adjust size as needed

        scene.getStylesheets().add(getClass().getResource("/style.css").toExternalForm());
        // Set the stage title
        stage.setTitle("Doctor's Plaza Management System");

        // Set the scene in the stage
        stage.setScene(scene);

        // Show the stage
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}


    
